### ISSUE TITLE
Restore values after restart Home Assistant

### ISSUE THREAD

**Issue by arboeh** [jugla/battery_consumption#2]
Nice work. I don't know if it's possible, but a property to restore attribute values after restarting Home Assistant would be nice.
The variables component (https://github.com/rogro82/hass-variables) has such a feature.

**Comment by jugla** [comment]
Hello,
Thanks for your feed back!
I will do something respect to restore feature !

**Comment by arboeh** [comment]
Wow, thanks for the quick answer.
Something like this would be nice:

```
restore_energy_charge: true
restore_energy_discharge: false
restore_battery_charge: true
restore_battery_discharge: true
```

Thanks in advance!

**Comment by jugla** [comment]
Hello,
I check the source and I have already put a restore feature. The restore is done at each restart.
I have implemented no option, since I recompute everything.
```py
    async def async_added_to_hass(self):
        """Handle added to Hass."""
        # restore from previous run
        await super().async_added_to_hass()
        state_recorded = await self.async_get_last_state()
        if state_recorded:
            ....
 ```

**Comment by jugla** [comment]
Hello,
Perhaps you wanted to have a specific beahaviour ?
Tell me.

**Comment by jugla** [comment]
No news.
I close the issue.
If you need a specific beahviour tell me.
