### ISSUE TITLE
WARNING Entity  is using state class 'measurement' which is impossible considering device class ('energy') it is using

### ISSUE THREAD

**Issue by danielbrunt57** [jugla/battery_consumption#3]
[Your documentation examples](https://github.com/jugla/battery_consumption#typical-use) indicate using state_class: measurement with device_class: energy but that seems to be invalid in HA...
```
023-02-02 22:00:57.838 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.front_door_lock_total_discharge (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
```
[Entities not representing a total amount](https://developers.home-assistant.io/docs/core/entity/sensor/#entities-not-representing-a-total-amount)
"The state_class property must be set to measurement, and the device_class must not be either of energy, gas, or monetary"

What `state_class` /`device_class:` should I be using?
`device_class: energy` & `state-class: total` ?

**Comment by jugla** [comment]
Sorry for the delay.
You're right.
Use
```yaml
        device_class: energy
        state_class: total
```

**Comment by jugla** [comment]
I have updated the documentation

**Comment by jugla** [comment]
Thanks for your issue, I close it since corrected by documentation.
